### ISSUE TITLE
При завантаженні файлової виписки УкрСибБанк помилка

### ISSUE THREAD

**Issue by VSydorenko** [VSydorenko/SMP_BankExchange#5]
При завантаженні файлової виписки УкрСибБанк, помилка: 
![image](https://github.com/VSydorenko/SMP_BankExchange/assets/50884937/7326e298-29fa-4f2b-ab61-65ed16b0cb5d)

**Comment by YaroslavHolovatiy** [comment]
Помилка була в порівнянні дати з типом "дата" та рядка з даними дати.
